apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: IMAGE
  value: maistra/istio-operator:0.1.0
- name: PULL_POLICY
  value: Always
- name: NAMESPACE
  value: istio-operator
- name: RELEASE
  value: v3.10
- name: MASTER_PUBLIC_URL
  value: https://127.0.0.1:8443
objects:

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: installations.istio.openshift.com
    labels:
      name: istio-operator
  spec:
    group: istio.openshift.com
    names:
      kind: Installation
      plural: installations
      singular: installation
    scope: Namespaced
    version: v1alpha1


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: ${NAMESPACE}
    name: istio-operator
    labels:
      name: istio-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: istio-operator
    template:
      metadata:
        labels:
          name: istio-operator
      spec:
        containers:
        - name: istio-operator
          image: ${IMAGE}
          imagePullPolicy: ${PULL_POLICY}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - istio-operator
          args:
          - "--release=${RELEASE}"
          - "--masterPublicURL=${MASTER_PUBLIC_URL}"
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: "istio-operator"
